version: '3.8'
# Master Password: wnuh-yhfc-6gta
services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - odoo_network

  odoo:
    image: odoo:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8069:8069"
    volumes:
      - ./tip_tracker:/mnt/extra-addons/tip_tracker
      - ./odoo.conf:/etc/odoo/odoo.conf
      - odoo_filestore:/var/lib/odoo/filestore
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
      - DEV_MODE=1
    user: root
    networks:
      - odoo_network
    command: >
      bash -c "chown -R odoo:odoo /var/lib/odoo/filestore && 
      sleep 10 && 
      odoo -c /etc/odoo/odoo.conf -i base --stop-after-init --without-demo=all && 
      odoo -c /etc/odoo/odoo.conf -i web --stop-after-init --without-demo=all && 
      odoo -c /etc/odoo/odoo.conf --without-demo=all"

volumes:
  odoo_postgres_data:
  odoo_filestore:

networks:
  odoo_network:
    driver: bridge 